image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  script:
    - npm ci
    - npm test
  artifacts:
    paths:
      - node_modules
